spring:
  application:
    name: go-event-flow-spring-boot
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_NAME}
  ai:
    vertex:
      ai:
        embedding:
          project-id: ${PROJ_ID}
          location: ${EMBEDDING_LOCATION}
          text:
            options:
              model: text-embedding-004
        gemini:
          project-id: ${PROJ_ID}
          location: ${GEMINI_LOCATION}
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.5
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rest:
  prefix: /go-event-flow

project:
  version: "@project.version@"

domain:
  back: ${BACK_URI:http://localhost:8080}
  front: ${VITE_API_URL:http://localhost:5173}

cors:
  allowed-headers: Authorization, Cache-Control, Content-Type, AcceptLanguage
  allowed-origins: ${domain.front}
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
  exposed-headers: Authorization

app:
  security:
    permitAllUris: >
      ${rest.prefix}/users/hello,
      ${rest.prefix}/auth/**,
      /swagger-ui/**,
      /v3/api-docs/**,
      /socket
    securedUris: ${rest.prefix}/**

jwt:
  secret: ${JWT_SECRET}
  expiration-time-minutes: 10
  refresh-token-expiration-days: 1

mail:
  templates:
    folder:  mail-templates/